[package]
name = "conf_parser"
version = "0.1.4"
edition = "2021"
authors = ["tee8z"]
description = "simple small library for handling conf files"
readme = "README.md"
repository = "https://github.com/tee8z/conf_parser"
license = "MIT"

[dependencies]
